2025-04-10 23:21 - INFO - Fetching controls...
2025-04-10 23:21 - INFO - Executing controls...
2025-04-10 23:28 - INFO - Fetching controls...
2025-04-10 23:28 - INFO - Executing controls...
2025-04-10 23:28 - INFO - No instances found. Skipping Control compute_public_instance...
2025-04-14 22:39 - INFO - Fetching controls...
2025-04-14 22:39 - INFO - Executing controls...
2025-04-14 22:39 - INFO - Creating Inventory of instances...
2025-04-14 22:45 - INFO - Fetching controls...
2025-04-14 22:45 - INFO - Executing controls...
2025-04-14 22:45 - INFO - Executing control: compute_old_instance
2025-04-14 22:45 - ERROR - 1TypeError[13] -- 'InstanceContainer' object is not iterable
2025-04-14 22:45 - INFO - Fetching controls...
2025-04-14 22:45 - INFO - Executing controls...
2025-04-14 22:45 - INFO - Executing control: compute_old_instance
2025-04-14 22:45 - ERROR - 1TypeError[13] -- 'InstanceContainer' object is not subscriptable
2025-04-14 22:48 - INFO - Fetching controls...
2025-04-14 22:48 - INFO - Executing controls...
2025-04-14 22:48 - INFO - Executing control: compute_old_instance
2025-04-14 22:51 - INFO - Fetching controls...
2025-04-14 22:51 - INFO - Executing controls...
2025-04-14 22:51 - INFO - Executing control: compute_old_instance
2025-04-14 22:52 - INFO - Fetching controls...
2025-04-14 22:52 - INFO - Executing controls...
2025-04-14 22:52 - INFO - Executing control: compute_old_instance
2025-04-14 22:53 - INFO - Fetching controls...
2025-04-14 22:53 - INFO - Executing controls...
2025-04-14 22:53 - INFO - Executing control: compute_old_instance
2025-04-14 22:55 - INFO - Fetching controls...
2025-04-14 22:55 - INFO - Executing controls...
2025-04-14 22:55 - INFO - Executing control: compute_old_instance
2025-04-14 22:55 - ERROR - 1AttributeError[14] -- 'Instance' object has no attribute 'created_at'
2025-04-14 22:56 - INFO - Fetching controls...
2025-04-14 22:56 - INFO - Executing controls...
2025-04-14 22:56 - INFO - Executing control: compute_old_instance
2025-04-14 22:56 - ERROR - 1AttributeError[14] -- 'Instance' object has no attribute 'created_at'
2025-04-14 22:56 - INFO - Fetching controls...
2025-04-14 22:56 - INFO - Executing controls...
2025-04-14 22:56 - INFO - Executing control: compute_old_instance
2025-04-14 22:56 - ERROR - 1AttributeError[14] -- 'Instance' object has no attribute 'created_at'
2025-04-14 22:56 - INFO - Fetching controls...
2025-04-14 22:56 - INFO - Executing controls...
2025-04-14 22:56 - INFO - Executing control: compute_old_instance
2025-04-14 22:57 - INFO - Fetching controls...
2025-04-14 22:57 - INFO - Executing controls...
2025-04-14 22:57 - INFO - Executing control: compute_old_instance
2025-04-14 22:59 - INFO - Fetching controls...
2025-04-14 22:59 - INFO - Executing controls...
2025-04-14 22:59 - INFO - Executing control: compute_old_instance
2025-04-14 23:00 - INFO - Fetching controls...
2025-04-14 23:00 - INFO - Executing controls...
2025-04-14 23:00 - INFO - Executing control: compute_old_instance
2025-04-14 23:03 - INFO - Fetching controls...
2025-04-14 23:03 - INFO - Executing controls...
2025-04-14 23:03 - ERROR - PydanticSchemaGenerationError[8] -- Unable to generate pydantic-core schema for <class 'exoscan.lib.controls.models.Template'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.11/u/schema-for-unknown-type
2025-04-14 23:03 - INFO - Fetching controls...
2025-04-14 23:03 - INFO - Executing controls...
2025-04-14 23:03 - ERROR - PydanticSchemaGenerationError[8] -- Unable to generate pydantic-core schema for <class 'exoscan.lib.controls.models.Template'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.11/u/schema-for-unknown-type
2025-04-14 23:04 - INFO - Fetching controls...
2025-04-14 23:04 - INFO - Executing controls...
2025-04-14 23:04 - ERROR - PydanticSchemaGenerationError[8] -- Unable to generate pydantic-core schema for <class 'exoscan.lib.controls.models.Template'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.11/u/schema-for-unknown-type
2025-04-14 23:05 - INFO - Fetching controls...
2025-04-14 23:05 - INFO - Executing controls...
2025-04-14 23:05 - INFO - Executing control: compute_old_instance
2025-04-14 23:06 - INFO - Fetching controls...
2025-04-14 23:06 - INFO - Executing controls...
2025-04-14 23:06 - INFO - Executing control: compute_old_instance
2025-04-14 23:06 - ERROR - 1AttributeError[14] -- 'dict' object has no attribute 'created_at'
2025-04-14 23:08 - INFO - Fetching controls...
2025-04-14 23:08 - INFO - Executing controls...
2025-04-14 23:08 - INFO - Executing control: compute_old_instance
2025-04-14 23:08 - ERROR - 1AttributeError[14] -- 'dict' object has no attribute 'created_at'
2025-04-14 23:09 - INFO - Fetching controls...
2025-04-14 23:09 - INFO - Executing controls...
2025-04-14 23:09 - INFO - Executing control: compute_old_instance
2025-04-14 23:09 - ERROR - 1AttributeError[14] -- 'dict' object has no attribute 'created_at'
2025-04-14 23:11 - INFO - Fetching controls...
2025-04-14 23:11 - INFO - Executing controls...
2025-04-14 23:11 - INFO - Executing control: compute_old_instance
2025-04-14 23:13 - INFO - Fetching controls...
2025-04-14 23:13 - INFO - Executing controls...
2025-04-14 23:13 - ERROR - 1AttributeError[9] -- 'dict' object has no attribute 'instances'
2025-04-14 23:17 - INFO - Fetching controls...
2025-04-14 23:17 - INFO - Executing controls...
2025-04-14 23:17 - ERROR - 1AttributeError[9] -- 'dict' object has no attribute 'instances'
2025-04-14 23:18 - INFO - Fetching controls...
2025-04-14 23:18 - INFO - Executing controls...
2025-04-14 23:18 - ERROR - 1AttributeError[9] -- 'dict' object has no attribute 'instances'
2025-04-14 23:22 - INFO - Fetching controls...
2025-04-14 23:22 - INFO - Executing controls...
2025-04-14 23:22 - INFO - Executing control: compute_old_instance
2025-04-14 23:23 - INFO - Fetching controls...
2025-04-14 23:23 - INFO - Executing controls...
2025-04-14 23:23 - INFO - Executing control: compute_old_instance
2025-04-14 23:26 - INFO - Fetching controls...
2025-04-14 23:26 - INFO - Executing controls...
2025-04-14 23:26 - ERROR - 1AttributeError[9] -- type object 'datetime.datetime' has no attribute 'timezone'
2025-04-14 23:26 - INFO - Fetching controls...
2025-04-14 23:26 - INFO - Executing controls...
2025-04-14 23:26 - ERROR - 1AttributeError[10] -- module 'datetime' has no attribute 'now'
2025-04-14 23:29 - INFO - Fetching controls...
2025-04-14 23:29 - INFO - Executing controls...
2025-04-14 23:29 - INFO - Executing control: compute_old_instance
2025-04-14 23:30 - INFO - Fetching controls...
2025-04-14 23:30 - INFO - Executing controls...
2025-04-14 23:30 - INFO - Executing control: compute_old_instance
2025-04-14 23:30 - INFO - Fetching controls...
2025-04-14 23:30 - INFO - Executing controls...
2025-04-14 23:30 - INFO - Executing control: compute_old_instance
2025-04-14 23:32 - INFO - Fetching controls...
2025-04-14 23:32 - INFO - Executing controls...
2025-04-14 23:32 - INFO - Executing control: compute_old_instance
2025-04-15 00:03 - INFO - Fetching controls...
2025-04-15 00:03 - INFO - Executing controls...
2025-04-15 00:03 - ERROR - ValidationError[9] -- 2 validation errors for Finding
ControlMetadata
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
ResourceDescription
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-15 00:04 - INFO - Fetching controls...
2025-04-15 00:04 - INFO - Executing controls...
2025-04-15 00:04 - ERROR - ValidationError[9] -- 2 validation errors for Finding
ControlMetadata
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
ResourceDescription
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-15 00:05 - INFO - Fetching controls...
2025-04-15 00:05 - INFO - Executing controls...
2025-04-15 00:05 - ERROR - ImportError[8] -- cannot import name 'Finding' from 'exoscan.lib.controls.models' (c:\Users\Iceman\Documents\exoscan\exoscan\lib\controls\models.py)
2025-04-15 00:05 - INFO - Fetching controls...
2025-04-15 00:05 - INFO - Executing controls...
2025-04-15 00:05 - INFO - Executing control: compute_old_instance
2025-04-15 00:21 - INFO - Fetching controls...
2025-04-15 00:21 - INFO - Executing controls...
2025-04-15 00:21 - INFO - Executing control: compute_old_instance
2025-04-15 00:21 - ERROR - 1FileNotFoundError[21] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\.metadata.json'
2025-04-15 00:23 - INFO - Fetching controls...
2025-04-15 00:23 - INFO - Executing controls...
2025-04-15 00:23 - INFO - Executing control: compute_old_instance
2025-04-15 00:23 - ERROR - 1FileNotFoundError[21] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\.metadata.json'
2025-04-15 00:28 - INFO - Fetching controls...
2025-04-15 00:28 - INFO - Executing controls...
2025-04-15 00:29 - INFO - Executing control: compute_old_instance
2025-04-15 00:29 - ERROR - 1TypeError[21] -- Finding.from_metadata() got an unexpected keyword argument 'rel_path'
2025-04-15 00:29 - INFO - Fetching controls...
2025-04-15 00:29 - INFO - Executing controls...
2025-04-15 00:29 - INFO - Executing control: compute_old_instance
2025-04-15 00:29 - ERROR - 1FileNotFoundError[21] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\compute\\instances\\compute_old_instance\\.metadata.json'
2025-04-15 00:29 - INFO - Fetching controls...
2025-04-15 00:29 - INFO - Executing controls...
2025-04-15 00:29 - INFO - Executing control: compute_old_instance
2025-04-15 00:29 - ERROR - 1FileNotFoundError[21] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\compute\\instances\\compute_old_instance\\compute_old_instance.py\\.metadata.json'
2025-04-15 00:32 - INFO - Fetching controls...
2025-04-15 00:32 - INFO - Executing controls...
2025-04-15 00:32 - ERROR - TypeError[11] -- execute_logic() missing 1 required positional argument: 'metadata_path'
2025-04-15 22:46 - INFO - Fetching controls...
2025-04-15 22:46 - INFO - Executing controls...
2025-04-15 22:46 - ERROR - TypeError[11] -- execute_logic() missing 1 required positional argument: 'metadata_path'
2025-04-15 22:47 - INFO - Fetching controls...
2025-04-15 22:47 - INFO - Executing controls...
2025-04-15 22:47 - ERROR - TypeError[11] -- execute_logic() missing 1 required positional argument: 'metadata_path'
2025-04-15 22:52 - INFO - Fetching controls...
2025-04-15 22:52 - INFO - Executing controls...
2025-04-15 22:52 - ERROR - TypeError[11] -- execute_logic() missing 1 required positional argument: 'metadata_path'
2025-04-15 22:53 - INFO - Fetching controls...
2025-04-15 22:53 - INFO - Executing controls...
2025-04-15 22:53 - ERROR - TypeError[11] -- execute_logic() missing 1 required positional argument: 'metadata_path'
2025-04-15 22:54 - INFO - Fetching controls...
2025-04-15 22:54 - INFO - Executing controls...
2025-04-15 22:54 - ERROR - TypeError[10] -- execute_logic() missing 1 required positional argument: 'metadata_path'
2025-04-15 22:54 - INFO - Fetching controls...
2025-04-15 22:54 - INFO - Executing controls...
2025-04-15 22:54 - INFO - Executing control: compute_old_instance
2025-04-15 22:54 - ERROR - 1FileNotFoundError[23] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\compute\\instances\\compute_old_instance\\.metadata.json'
2025-04-15 23:02 - INFO - Fetching controls...
2025-04-15 23:02 - INFO - Executing controls...
2025-04-15 23:02 - ERROR - TypeError[13] -- execute_logic() takes 0 positional arguments but 1 was given
2025-04-15 23:02 - INFO - Fetching controls...
2025-04-15 23:02 - INFO - Executing controls...
2025-04-15 23:02 - INFO - Executing control: compute_old_instance
2025-04-15 23:02 - ERROR - 1FileNotFoundError[23] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\compute\\instances\\compute_old_instance\\.metadata.json'
2025-04-15 23:05 - INFO - Fetching controls...
2025-04-15 23:05 - INFO - Executing controls...
2025-04-15 23:05 - ERROR - AttributeError[12] -- 'WindowsPath' object has no attribute 'rstrip'
2025-04-15 23:07 - INFO - Fetching controls...
2025-04-15 23:07 - INFO - Executing controls...
2025-04-15 23:07 - ERROR - AttributeError[13] -- 'WindowsPath' object has no attribute 'rstrip'
2025-04-15 23:09 - INFO - Fetching controls...
2025-04-15 23:09 - INFO - Executing controls...
2025-04-15 23:09 - INFO - Executing control: compute_old_instance
2025-04-15 23:09 - ERROR - 1FileNotFoundError[23] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\compute\\instances\\compute_old_instance\\.metadata.json'
2025-04-15 23:10 - INFO - Fetching controls...
2025-04-15 23:10 - INFO - Executing controls...
2025-04-15 23:10 - INFO - Executing control: compute_old_instance
2025-04-15 23:10 - ERROR - 1FileNotFoundError[23] -- [Errno 2] No such file or directory: 'c:\\Users\\Iceman\\Documents\\exoscan\\exoscan\\lib\\controls\\compute\\instances\\compute_old_instance\\.metadata.json'
2025-04-15 23:11 - INFO - Fetching controls...
2025-04-15 23:11 - INFO - Executing controls...
2025-04-15 23:11 - INFO - Executing control: compute_old_instance
2025-04-15 23:11 - ERROR - TypeError[17] -- execute_logic() takes 0 positional arguments but 1 was given
2025-04-15 23:12 - INFO - Fetching controls...
2025-04-15 23:12 - INFO - Executing controls...
2025-04-15 23:12 - INFO - Executing control: compute_old_instance
2025-04-15 23:12 - INFO - Fetching controls...
2025-04-15 23:12 - INFO - Executing controls...
2025-04-15 23:12 - INFO - Executing control: compute_old_instance
2025-04-15 23:14 - INFO - Fetching controls...
2025-04-15 23:14 - INFO - Executing controls...
2025-04-15 23:14 - INFO - Executing control: compute_old_instance
2025-04-15 23:15 - INFO - Fetching controls...
2025-04-15 23:15 - INFO - Executing controls...
2025-04-15 23:15 - INFO - Executing control: compute_old_instance
2025-04-15 23:16 - INFO - Fetching controls...
2025-04-15 23:16 - INFO - Executing controls...
2025-04-15 23:16 - INFO - Executing control: compute_old_instance
2025-04-15 23:17 - INFO - Fetching controls...
2025-04-15 23:17 - INFO - Executing controls...
2025-04-15 23:17 - INFO - Executing control: compute_old_instance
2025-04-15 23:17 - ERROR - TypeError[17] -- 'NoneType' object is not iterable
2025-04-15 23:19 - INFO - Fetching controls...
2025-04-15 23:19 - INFO - Executing controls...
2025-04-15 23:19 - INFO - Executing control: compute_old_instance
